from collections import OrderedDict, Counter
def nucleotide_counter(sequence):
    """
    :param s: A DNA string s of length at most 1000 nt.
    :return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.
    """
    cnt = Counter()
    l = []
    #1) Count the letters
    for base in sequence:
        cnt[base] +=1
    #2) Order the dictionary so that it outputs the counts for A, C, G, T in that order
    cnt_2 = OrderedDict(sorted(cnt.items()))
    #3) Put the values in a list
    for key, value in cnt_2.items():
        l.append(str(value))
    #4) Formatting
    counts = ' '.join(l)
    return counts

if __name__ == "__main__":
    s = "CGCACAGGTACCCTCCGAGCGAAATGTCCATTATCATCCTATGCAATCGGTCAGATCTCTTCCGGATTGTGATATCGGGCCATTATCAGGGGCGCTCTTCCAAACATACACTACCGTCCCGGACGCTTATCGGTAATAGCCAACCCCTACATGGAGCATTCGGTAATGAACATATCTGAATGCAGAAGTTCTATGGGTGCAATTTCGTTATCCCCTGGTGCCAATGGTATCGTCCCGGCCACGAGGATTGGCTCACGTACCACACGCCTTCCCAATTCGTACAGAGACTGCTGCGCGATGCCCTAATGTAGCTAAGACCCCTCATTTGGCGGCAACCCATACCTTACGTCCCCAATCTAGGCTCGATTCCAGTGGAAGAGTAGCACTTGCATTCAATCTCGCATAGGAATCTTATAGCTCAGCACTTTACTCAGGTTCAACCTCGGCTCTTAACGCGATGCGAAAACAATATCCAAGGAATCCGCTAAACGCGGGTATGCGAGTTGGGGGGCCATTCACGAGTCCGTGGTGAATTAGTAGCCCATTTTTGACAAACGACTACGGTGGCGGTCAATGGTCCGGTATCTGTAGCCTCCTAGCCCGTGTGTCGTATGCTAGAGGGATGAGAGTCCGATGGATTGTCACTCAGGCAATCGAGATCCGCAAACCTGACGATGCGTTAAGACGATTCTTGTGGCTTTAGTGAGATTCGAGAGATTGCCGACTGGATTTGTGAGTCTATATGTTAGCCACCCTGCGCCATAAATGCGCAGCCATTAAAATAACTAACATTCCAAGGGTGTATTCCCTCAATGAACTATCTGAGCGAGAACCACAGTAGGTCAAAGTGGATGGCAGGGATGGTGCCGTTATACGA"
    answer = nucleotide_counter(s)
    print answer




